services:
  external-api:
    image: node:22.8.0-slim
    command: npx json-server --watch api.json --port 8000
    ports:
      - 8000:8000
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
