include:
  - ./external-api/docker-compose.external-api.yaml

services:
  web1:
    extends:
      file: docker-compose.common.yaml
      service: web
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  web2:
    extends:
      file: docker-compose.common.yaml
      service: web
    ports:
      - 3001:3000
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.19.1-alpine
    restart: always
    ports:
      - 4000:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    # networks:
    #   - external-api_default

# networks:
#   external-api_default:
#     external: true
