FROM node:22.8.0-slim

ARG NODEMON_VERSION=3.1.7

RUN apt update && \
    apt install -y curl && \
    npm install -g nodemon@${NODEMON_VERSION}

# debian
# RUN useradd -m -u 1000 xpto # create user
# RUN usermod -u 1000 xpto

# alpine
# RUN adduser -D -u 1000 xpto # create user
# RUN sed -i 's/1000/1001/g' /etc/passwd

COPY start.sh /
RUN chmod +x /start.sh

USER node

WORKDIR /home/node/app

COPY package.json ./
RUN npm install

EXPOSE 3000

CMD ["npm", "start"]
